version: "3.5"

services:
  verbalizelt:
    container_name: verbalizelt-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
